# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script:
    git config --global user.email "richardkneale@hotmail.co.uk"
  displayName: 'Set email'

- script:
    git config --global user.name "git145"
  displayName: 'Set name'

- script:
    git pull https://github.com/git145/CosmosDb.Gremlin.git master
  displayName: 'Pull from GitHub'

- script:
    git push https://$(gitHubPersonalToken)@github.com/git145/CosmosDb.Gremlin.git HEAD:master
  displayName: 'Push to GitHub'
