# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script:
    git pull --allow-unrelated-histories https://github.com/git145/CosmosDb.Gremlin master
  displayName: 'Pull from GitHub'

- script:
    git push https://$(gitHubPersonalToken)@https://github.com/git145/CosmosDb.Gremlin HEAD:master
  displayName: 'Push to GitHub'
